### ISSUE TITLE
Could I use Capsule to deflate a view?

### ISSUE THREAD

**Issue by aliasone** [HenrikJoreteg/Capsule#10]
Could I use Capsule to deflate a view to JSON send it somewhere via websockets and then inflate the view again?

We have an experimental application and one of its goals is to use only websockets after the initial payload. In one case we want to do something where a user could be accessing 1 of 500 different interactive widgets. We're using Capsule to dynamically pass a model for each when needed and we want to do something similar with views. 

Possible? Thanks for any feedback.

**Comment by HenrikJoreteg** [comment]
Building a websockets only app is awesome! I'm doing it right now, in fact.

Hmm, there'a really not much data to serialize in a view is there?
There shouldn't be any, IMO.

If you're talking about a template, you _could_ set a template string
as one of the model properties?? But it depends what you're trying to
do.

It sounds like an interesting project. Our team may have a bit of
availability for consulting if you need more involved help, or want
help actually writing some code.

Either way, I'm quite curious what you're up to.

Cheers!
- Henrik

On Oct 21, 2011, at 2:00, aliasone
reply@reply.github.com
wrote:

**Comment by aliasone** [comment]
Sorry, I don't think I asked that questions too well. We want to be able to pull new views(listeners/methods) from the server dynamically via websockets, including templates, and instantiate new backbone views from the data sent over the websocket.
