### ISSUE TITLE
Would you recommend using Capsule client-side only?

### ISSUE THREAD

**Issue by aliasone** [HenrikJoreteg/Capsule#9]
I'd like to use Capsule a little differently then it was designed. Could I keep the collapsed model state in mongo on the server and interact with the raw data without creating backbone models?

The goal would be to use it for syncing (collapsing/rebuilding) sub-models across different clients. The server will be acting more like a pneumatic tube routing the capsule to the clients that need it yet still maintaing the ability to alter the data using its own methods unrelated to backbone. 

Thanks

**Comment by HenrikJoreteg** [comment]
As a mentioned in the readme, keeping full shared state on the server doesn't scale well. The problem with most traditional databases is the lack of eventing. Luckily there's redis. That's what we've been using to overcome this problem. I still share models between server/client but don't keep them on the server when I'm done with them. There will be much blogging about this later. Essentially, yes, I use Capsule primarily on the client-side these days with thoonk/redis as the back-end.

**Comment by aliasone** [comment]
Thanks Henrik,

I'd love to see some how you're going about things these days. My main concern not having backbone models live on the server all the time is handeling updates. Writing handlers for every possible change defeats the purpose, but I can't just overwrite model data on the fly either.

**Comment by HenrikJoreteg** [comment]
When we've fully launched &! (http://andbang.com) we'll blog it up about how we're doing things. Not really any time to write it up just yet, as we're still tweaking a lot of stuff. There will be some great conversation about this stuff at http://krtconf.com too.

**Comment by aliasone** [comment]
Awesome. 

Will krtconf talks will be online afterwards? I can't make it this year.

**Comment by HenrikJoreteg** [comment]
They probably will, not sure exactly when, but they will be recorded. Nothing like being there and getting to talk to all those people in person. But I know how it goes.
